title: YZ's homepage
url: "https://yuanzhen214.github.io"
baseurl: "/"

markdown: kramdown
# ins_logo: "./bits-logo.png"  ## 顶端图标

tracking_id: #

footer: yes
footer_url: " "
footer_text: "返回顶端"

sass:
    style: compressed
    sass_dir: _sass

# nav:
# #  - name: "记录"
# #    link: "/"
# #  - name: "Resume"
# #    link: "resume.pdf"
#  - name: "Contact"
#    link: "contact"
